import { useEffect, useState } from "react";
import { ArrowLeft, ExternalLink, ShieldCheck } from "lucide-react";
import { useNavigate, useParams } from "react-router";
import { isSupabaseConfigured, requireSupabase } from "../lib/supabase";

type E={id:string;event_name:string;country:string;currency:string|null;event_time:string;importance:string;previous:number|null;forecast:number|null;actual:number|null;status:string;category:string|null;related_asset:string|null};
type S={scenario_type:string;confidence:number;reasoning:string;gold_impact:string;supporting_factors:string[];counter_factors:string[]};
type I={indicator_name:string;latest_value:number|null;previous_value:number|null;direction:string;relevance:number;source_name:string|null};
type H={release_date:string;previous:number|null;forecast:number|null;actual:number|null;surprise:number|null;gold_reaction:string|null};
type Source={source_name:string;source_url:string;source_verified:boolean;published_at:string|null;retrieved_at:string};

const date=(v:string)=>new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(v));
const time=(v:string)=>new Intl.DateTimeFormat("id-ID",{hour:"2-digit",minute:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date(v))+" WIB";
const label=(x:string)=>x==="above_forecast"?"ABOVE FORECAST":x==="below_forecast"?"BELOW FORECAST":"NEAR FORECAST";

function Panel({children,className=""}:{children:React.ReactNode;className?:string}){return <div className={"rounded-xl border border-[#1c2938] bg-[#0c121c] "+className}>{children}</div>}
function Badge({children,green=false}:{children:React.ReactNode;green?:boolean}){return <span className={"inline-flex rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide "+(green?"border-emerald-400/20 bg-emerald-400/10 text-emerald-300":"border-sky-400/20 bg-sky-400/10 text-sky-300")}>{children}</span>}

export default function EconomicEventDetailPage(){
  const {eventId}=useParams(),nav=useNavigate();
  const [event,setEvent]=useState<E|null>(null),[scenarios,setScenarios]=useState<S[]>([]),[indicators,setIndicators]=useState<I[]>([]),[history,setHistory]=useState<H[]>([]),[sources,setSources]=useState<Source[]>([]),[error,setError]=useState("");
  useEffect(()=>{if(!eventId||!isSupabaseConfigured)return;const c=requireSupabase();void Promise.all([
    c.from("economic_events").select("*").eq("id",eventId).maybeSingle(),
    c.from("economic_event_scenarios").select("*").eq("event_id",eventId).order("confidence",{ascending:false}),
    c.from("economic_event_indicators").select("*").eq("event_id",eventId).order("relevance",{ascending:false}),
    c.from("economic_event_history").select("*").eq("event_id",eventId).order("release_date",{ascending:false}),
    c.from("economic_event_sources").select("*").eq("event_id",eventId).order("retrieved_at",{ascending:false})
  ]).then(([e,s,i,h,src])=>{if(e.error)setError(e.error.message);setEvent(e.data as E|null);setScenarios((s.data??[]) as S[]);setIndicators((i.data??[]) as I[]);setHistory((h.data??[]) as H[]);setSources((src.data??[]) as Source[])});},[eventId]);
  if(!isSupabaseConfigured)return <Panel className="p-10 text-center text-xs text-[#7f8da3]">Supabase belum dikonfigurasi.</Panel>;
  if(error)return <Panel className="p-10 text-center text-xs text-rose-300">{error}</Panel>;
  if(!event)return <Panel className="p-10 text-center text-xs text-[#7f8da3]">Loading event detail…</Panel>;
  const released=event.status==="released";
  return <div className="space-y-6">
    <button onClick={()=>nav("/economic-intelligence")} className="inline-flex items-center gap-2 text-xs text-[#7f8da3] hover:text-foreground"><ArrowLeft className="size-3.5"/>Back to AI Economic Intelligence</button>
    <section className="flex flex-col gap-4 border-b border-[#1c2938] pb-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="mb-2 flex flex-wrap gap-2"><Badge green={released}>{released?"RELEASED":"UPCOMING"}</Badge>{event.importance.toLowerCase()==="high"?<Badge>HIGH IMPACT</Badge>:null}{event.related_asset==="XAUUSD"?<Badge>XAUUSD RELEVANCE</Badge>:null}</div><h1 className="text-2xl font-semibold">{event.event_name}</h1><p className="mt-2 text-xs text-[#7f8da3]">{date(event.event_time)} · {time(event.event_time)} · {event.country} · {event.currency??"USD"}</p></div><div className="grid grid-cols-3 gap-2"><Metric name="Previous" value={event.previous}/><Metric name="Official Forecast" value={event.forecast}/><Metric name="Actual" value={event.actual}/></div></section>
    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
      <Panel><div className="border-b border-[#1c2938] p-5"><div className="text-sm font-semibold">AI EXPECTATION</div><div className="mt-1 text-[11px] text-[#7f8da3]">AI estimate is separate from official forecast and is not a guarantee.</div></div>{released?<div className="p-5 text-xs text-[#7f8da3]">Event is released. Use the historical section for forecast/actual and surprise context.</div>:scenarios.length?<div className="space-y-4 p-5"><div className="text-xl font-semibold text-sky-200">Potentially {label(scenarios[0].scenario_type)}</div><div className="flex items-center gap-2"><Badge>{Math.round(scenarios[0].confidence)}/100 confidence</Badge><span className="text-[10px] text-[#7f8da3]">model confidence, not market probability</span></div><div className="rounded-md border border-[#1c2938] bg-[#080d15] p-4 text-xs leading-5 text-[#7f8da3]">{scenarios[0].reasoning}</div><div className="grid gap-4 md:grid-cols-2"><Evidence title="SUPPORTING EVIDENCE" items={scenarios[0].supporting_factors}/><Evidence title="COUNTER EVIDENCE" items={scenarios[0].counter_factors}/></div><div className="rounded-md border border-sky-400/10 bg-sky-400/5 p-4"><div className="text-[9px] uppercase tracking-[.16em] text-sky-300/70">GOLD IMPACT</div><div className="mt-2 text-sm font-semibold">{scenarios[0].gold_impact}</div></div></div>:<div className="p-5 text-xs text-[#7f8da3]">Insufficient evidence to estimate the likely release.</div>}</Panel>
      <Panel><div className="border-b border-[#1c2938] p-5"><div className="text-sm font-semibold">OFFICIAL DATA</div><div className="mt-1 text-[11px] text-[#7f8da3]">No value is inferred when the source layer has no value.</div></div><div className="grid grid-cols-2 gap-3 p-5"><Metric name="Previous" value={event.previous}/><Metric name="Forecast" value={event.forecast}/><Metric name="Actual" value={event.actual}/><Metric name="Surprise" value={event.actual!=null&&event.forecast!=null?event.actual-event.forecast:null}/></div></Panel>
    </div>
    <Panel><div className="border-b border-[#1c2938] p-5"><div className="text-sm font-semibold">SUPPORTING DATA</div><div className="mt-1 text-[11px] text-[#7f8da3]">Economic indicators returned by the server-side data provider.</div></div>{indicators.length?<div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="border-b border-[#1c2938] text-[9px] uppercase tracking-[.16em] text-[#7f8da3]"><tr>{["Indicator","Latest","Previous","Direction","Relevance","Source"].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody>{indicators.map((x,i)=><tr key={x.indicator_name+i} className="border-b border-[#1c2938]/70 last:border-0"><td className="px-5 py-3 font-semibold">{x.indicator_name}</td><td className="px-5 py-3">{x.latest_value??"—"}</td><td className="px-5 py-3">{x.previous_value??"—"}</td><td className="px-5 py-3">{x.direction||"—"}</td><td className="px-5 py-3">{x.relevance}</td><td className="px-5 py-3 text-[#7f8da3]">{x.source_name??"—"}</td></tr>)}</tbody></table></div>:<div className="p-8 text-center text-xs text-[#7f8da3]">No supporting indicator data.</div>}</Panel>
    <div className="grid gap-5 xl:grid-cols-2"><Panel><div className="border-b border-[#1c2938] p-5"><div className="text-sm font-semibold">HISTORICAL DATA</div></div>{history.length?<div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead className="border-b border-[#1c2938] text-[9px] uppercase tracking-[.16em] text-[#7f8da3]"><tr>{["Date","Previous","Forecast","Actual","Surprise","Gold"].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody>{history.map((x,i)=><tr key={x.release_date+i} className="border-b border-[#1c2938]/70 last:border-0"><td className="px-5 py-3">{date(x.release_date)}</td><td className="px-5 py-3">{x.previous??"—"}</td><td className="px-5 py-3">{x.forecast??"—"}</td><td className="px-5 py-3">{x.actual??"—"}</td><td className="px-5 py-3">{x.surprise??"—"}</td><td className="px-5 py-3 text-[#7f8da3]">{x.gold_reaction??"—"}</td></tr>)}</tbody></table></div>:<div className="p-8 text-center text-xs text-[#7f8da3]">No historical records stored.</div>}</Panel><Panel><div className="border-b border-[#1c2938] p-5"><div className="flex items-center gap-2"><ShieldCheck className="size-4 text-emerald-300"/><div className="text-sm font-semibold">SOURCES</div></div></div>{sources.length?sources.map((s,i)=><div key={s.source_url+i} className="border-b border-[#1c2938]/70 p-4 last:border-0"><div className="flex items-center gap-2">{s.source_verified?<Badge green>SOURCE VERIFIED</Badge>:<Badge>UNVERIFIED</Badge>}<span className="text-[10px] text-[#7f8da3]">{s.source_name}</span></div><a href={s.source_url} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-[10px] text-sky-300 hover:underline">Open Source <ExternalLink className="size-3"/></a><div className="mt-2 text-[9px] text-[#7f8da3]">Published: {s.published_at?new Date(s.published_at).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Jakarta"})+" WIB":"—"} · Retrieved: {new Date(s.retrieved_at).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Jakarta"})+" WIB"}</div></div>):<div className="p-8 text-center text-xs text-[#7f8da3]">No source records.</div>}</Panel></div>
    <Panel><div className="border-b border-[#1c2938] p-5"><div className="text-sm font-semibold">MARKET SCENARIOS</div><div className="mt-1 text-[11px] text-[#7f8da3]">Above / Near / Below forecast remain alternative scenarios.</div></div><div className="grid gap-3 p-5 md:grid-cols-3">{scenarios.map(s=><div key={s.scenario_type} className="rounded-md border border-[#1c2938] bg-[#080d15] p-4"><div className="flex items-center justify-between"><div className="text-xs font-semibold">{label(s.scenario_type)}</div><Badge>{Math.round(s.confidence)}/100</Badge></div><div className="mt-3 text-[10px] leading-5 text-[#7f8da3]">{s.gold_impact}</div></div>)}</div></Panel>
  </div>
}
function Metric({name,value}:{name:string;value:number|null}){return <div className="rounded-md border border-[#1c2938] bg-[#080d15] p-3"><div className="text-[9px] uppercase tracking-[.14em] text-[#7f8da3]">{name}</div><div className="mt-2 text-sm font-semibold">{value??"—"}</div></div>}
function Evidence({title,items}:{title:string;items:string[]}){return <div><div className="text-[9px] uppercase tracking-[.15em] text-[#7f8da3]">{title}</div><div className="mt-2 space-y-2">{items?.length?items.map(x=><div key={x} className="rounded-md border border-[#1c2938] p-2.5 text-[10px]">{x}</div>):<div className="text-[10px] text-[#7f8da3]">None recorded.</div>}</div></div>}
